name: Deploy to AWS Lambda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --production

      - name: Create deployment package
        run: zip -r function.zip src/ node_modules/

      - name: Create or Update Lambda function
        run: |
          # Try to update first, if it fails, create the function
          if ! aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://function.zip; then
            
            echo "Function doesn't exist, creating it..."
            aws lambda create-function \
              --function-name my-lambda-function \
              --runtime nodejs18.x \
              --role arn:aws:iam::YOUR_ACCOUNT_ID:role/lambda-execution-role \
              --handler src/index.handler \
              --zip-file fileb://function.zip \
              --description "My Lambda function deployed via CI/CD"
          fi

      # - name: Run tests
      #   run: npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          zip -r function.zip src/ node_modules/
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://function.zip
